#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://${DB_HOST:beta-fl56.mysql.rds.aliyuncs.com}:${DB_PORT:3306}/${DB_NAME:eladmin}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: ${DB_USER:szfl}
      password: ${DB_PWD:szfl@2017}
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
      #数据库索引
      database: ${REDIS_DB:0}
      host: ${REDIS_HOST:10.0.5.202}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:}
      #连接超时时间
      timeout: 5000

# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# IP 本地解析
ip:
  local-parsing: true

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

# 日志配置
logback:
  dir: /Users/luobin/Documents/workspace/log/eladmin

# 消息配置
mq:
  access-key: LTAILrMIaxNYSloH
  secret-key: sMgf2lbtpJjevoyVWMtzXYSb8kbQXY
  addr: http://MQ_INST_1788072189104904_BXf4MMqC.mq-internet-access.mq-internet.aliyuncs.com:80
  cross-border-order-gid: GID_TEST_CB_ORDER
  order-topic: CB_TEST_ORDER
  cross-border-return-gid: GID_TEST_CB_RETURN
  return-topic: CB_TEST_RETURN
  bus-log-gid: GID_TEST_BUS_LOG
  bus-log-topic: BUS_TEST_LOG
  bus-domestic-order-gid: GID_DOMESTIC_TEST_ORDER
  bus-domestic-order-topic: DOMESTIC_TEST_ORDER

#快递配置
#express:
#  g-zto-companyid: CS11607257E11219
#  g-zto-key: C34EB3E757505996D4
#  g-zto-url: http://intltest.zto.cn/api/import/init

#快递配置
express:
  g-zto-companyid: NBFLWL1359487E30
  g-zto-key: 92FFDEFF4E1047A6CE
  g-zto-url: https://gjapi.zt-express.com
  dm-zto-companyid: 29565633d3224ef6985c29897708d65c
  dm-zto-key: ac3f2ffa3842
  dm-zto-partner: 1000027287
  dm-zto-verify: Y47AXU0R7P
  dm-zto-mail-url: http://japi.zto.cn/submitOrderCode
  dm-zto-mark-url: http://japi.zto.cn/bagAddrMarkGetmark


#抖音配置
#douyin:
#  url: http://openapi.jinritemai.com/
#  app-key: 6847386892158125582
#  app-secret: f1afd82e-68de-4b35-a8c8-c9039c432bf2
#  vender: NBFL

douyin:
  url: https://openapi-fxg.jinritemai.com/
  app-key: 6900812651828348424
  app-secret: 63415a7a-de83-43ea-a522-cb616c47a4ef
  vender: NBFL
  sorter-url: http://180.184.175.204:59987
  sorter-access-key: E141328A415F4A1681F36BFF264C75CC
  sorter-secret-key: 89DFDA1F5D981A747E57CD21A50246B8

# 得物配置
dewu:
  app-key: PXDRNkie1CtY1TW9
  app-secret: 8m92ZmhT0j0uF4KRtZJycP6guZJMm6
  base-url: http://t0-app.dewu.com

# 服务器域名
serverUrl: http://120.55.9.185
# 拼多多相关配置
pdd:
  signKey: 80db75f13e0e4dce80117e6591666d99
  url: http://pdd.fl56.net
  pddUserId: 795604644

# WMS配置
wms:
  data-hub:
    url: http://kjgapi.fl56.net:19192/datahub/FluxWmsJsonApi/
    app-key: 80AC1A3F-F949-492C-A024-7044B28C8025
    app-secret: 80AC1A3F-F949-492C-A024-7044B28C8025

# 圈尚配置   http://a436-39-170-57-17.ngrok.io    http://f9ba-39-170-60-16.ngrok.io     test.nbqs.cn
qs:
  url: test.nbqs.cn
  partner: 123456
  secret: 123456abcdef

# 卓志
zhuozhi:
  url-pms: http://106.75.165.2/pms
  app-key: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCDfAjAvaH8zU5unpsCn/604js5c61GMVhCBeCQ7FJ3m3Q==
  pub-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKkdWCQRfwEbtLwf0z4Ehdqu/Hu+lr6QzBBjSSFGVT3N8NFsucvNfhxr4VFWp28buUQXBEeF3nmn5Jfq+vuDFnA==

#蘑菇街
moGuJie:
  appKey: 102296
  appSecret: 51CC7068C6D80586C50765F1A9DE1D1F
  url: https://openapi.mogujie.com/invoke

#美团
meiTuan:
  appId: 7335
  appSecret: 277fb01858dc69791f1e8ac3bd0effa0
  url: http://22h73295e6.51mypc.cn


#邮政
EMS:
  partner_id: key123xydJDPT
  get-number-url: https://211.156.197.233/iwaybillno-web/a/iwaybill/receive
  dec-url: http://int.ems.com.cn:8080/kjjktbApi_Server/call.api
  ecommerce-no: HNHCYY
  ec-company-id: HNHCYY

SF:
  aes-key: YuBD6SOUSj3gJrPqukWGq0V6JbPB6vSi
  hmac-key: BNC6EwjTAoy1kmt2BMu6T4/ZJT092gHO
  partner-id: FLWLXX
  cust-id: 5744651295
  url: http://ESG-ISP-GW.sf-express.com/isp/ws/sfexpressService

ruoYuChen:
  appId: MTY0ODY5MjM4MzQxNA==
  appSecret: ZjYxMjg1ZWE1N2RjOGMzNDlkNGRkNDk5MzFhMjA1MTA=
  url: http://47.99.106.238:8080/stock/erp/send
  erpCode: ERP001

guoMei:
  key: 303d8cc1dc074d7ab2701d2ca65022a2
  signSecret: fd42b9a2725a412194087c44d74ea890
  apiUrl: http://silk.road.test.gome.com.cn
  vendor: VC004

jackYun:
  appId: 13261846
  secret: 63eb851b5e0d4b4fbd2c4443849250a3
  url: http://aliyun.polyapi.com/StorageNotify/Notify/337-EDI-978603-1403676435224462208